### ISSUE TITLE
Correct ranking index

### ISSUE THREAD

**Issue by mvendra** [blackbird-studios/coding-exercise-mvendra#1]
https://github.com/blackbird-studios/coding-exercise-mvendra/blob/aabb82b38106665e2a604509b754a43388b746b3/expected-output.txt#L5

The list goes 1, 2, 3, 3, then 5. Shouldn't the last one be indexed as "4" instead of "5" ?
Thanks.

@eagsalazar @amay

**Comment by amay** [comment]
Hi @mvendra thanks for the question. That ranking is intentional as there is a tie for 3rd place.

**Comment by mvendra** [comment]
@amay Thanks. I'll have that fixed and then submit the complete solution shortly.
